package com.tenure.domain.notification.enums;

public enum NotificationType {
    PRICE_CHANGED,
    SALE_STARTED,
    PURCHASE_INTENT_RECEIVED,
    PURCHASE_OFFER_RECEIVED,
    PURCHASE_INTENT_ACCEPTED,
    PURCHASE_OFFER_ACCEPTED,
    PURCHASE_INTENT_REJECTED,
    PURCHASE_OFFER_REJECTED,
    PURCHASE_REQUEST_EXPIRED,
    PURCHASE_REQUEST_SUPERSEDED,
    ITEM_SOLD,
    SHIPPING_STARTED,
    TRADE_STATUS_CHANGED,
    FOLLOW_REQUEST_RECEIVED,
    FOLLOW_REQUEST_ACCEPTED,
    TAG_REVIEW_REQUIRED
}
