CREATE TABLE recent_viewed_ootds
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viewer_user_id BIGINT         NOT NULL,
    ootd_id        BIGINT         NOT NULL,
    last_viewed_at TIMESTAMP(6)   NOT NULL,
    CONSTRAINT uk_recent_viewed_ootds_viewer_ootd UNIQUE (viewer_user_id, ootd_id),
    CONSTRAINT fk_recent_viewed_ootds_viewer FOREIGN KEY (viewer_user_id) REFERENCES users (id),
    CONSTRAINT fk_recent_viewed_ootds_ootd FOREIGN KEY (ootd_id) REFERENCES ootds (id)
);
