-- 회원 탈퇴(소프트 삭제 + 익명화) 지원

-- 1) users 에 탈퇴 시각 컬럼 추가
ALTER TABLE users ADD COLUMN deleted_at TIMESTAMP(6);

-- 2) 탈퇴 시 이메일/비밀번호를 비우기 위해 NOT NULL 제약 해제
--    (username은 '탈퇴한 사용자'로 대체, NOT NULL 유지)
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;

-- 3) 기존 email unique 제약을 "탈퇴하지 않은 회원끼리만 유일"로 변경
--    -> 탈퇴한 계정의 이메일은 비워지므로, 같은 이메일로 재가입 가능
ALTER TABLE users DROP CONSTRAINT IF EXISTS uk_users_email;
CREATE UNIQUE INDEX uk_users_email_active
    ON users (email) WHERE email IS NOT NULL AND deleted_at IS NULL;

-- 4) 탈퇴 사유 저장 테이블
CREATE TABLE user_withdrawals (
                                  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  user_id     BIGINT      NOT NULL,
                                  reason      VARCHAR(50) NOT NULL,
                                  created_at  TIMESTAMP(6) NOT NULL,
                                  CONSTRAINT fk_user_withdrawals_user FOREIGN KEY (user_id) REFERENCES users (id)
);