CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255),
    username VARCHAR(30) NOT NULL,
    profile_image_url VARCHAR(500),
    gender VARCHAR(20) NOT NULL,
    height_cm INTEGER NOT NULL,
    weight_kg INTEGER NOT NULL,
    grade VARCHAR(20) NOT NULL DEFAULT 'BASIC',
    account_visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
    default_shipping_fee INTEGER,
    default_fee_policy VARCHAR(30),
    default_purchase_offer_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    notification_settings JSONB,
    settlement_account JSONB,
    onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT ck_users_gender CHECK (gender IN ('MALE', 'FEMALE')),
    CONSTRAINT ck_users_grade CHECK (grade IN ('BASIC', 'RECORD')),
    CONSTRAINT ck_users_account_visibility CHECK (account_visibility IN ('PUBLIC', 'PRIVATE')),
    CONSTRAINT ck_users_default_fee_policy CHECK (
        default_fee_policy IS NULL
        OR default_fee_policy IN ('SELLER_PAYS', 'BUYER_PAYS', 'SPLIT')
    )
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name VARCHAR(50) NOT NULL,
    depth INTEGER NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories (id)
);

CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    brand_name VARCHAR(100) NOT NULL,
    item_name VARCHAR(100) NOT NULL,
    wearing_target VARCHAR(20) NOT NULL,
    size_system VARCHAR(30),
    size_value VARCHAR(30),
    representative_image_url VARCHAR(500),
    item_status VARCHAR(30) NOT NULL DEFAULT 'OWNED',
    ootd_verified_wear_count INTEGER NOT NULL DEFAULT 0,
    last_worn_at DATE,
    first_owned_at DATE,
    wish_count INTEGER NOT NULL DEFAULT 0,
    purchase_offer_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_items_owner FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT fk_items_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT ck_items_wearing_target CHECK (wearing_target IN ('MENSWEAR', 'WOMENSWEAR', 'UNISEX')),
    CONSTRAINT ck_items_item_status CHECK (
        item_status IN ('OWNED', 'ON_SALE', 'SOLD', 'TRANSFERRED', 'ARCHIVED')
    )
);

CREATE TABLE delivery_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    receiver_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255) NOT NULL,
    postal_code VARCHAR(10),
    request_note VARCHAR(300),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_delivery_addresses_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE ootds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    source VARCHAR(20) NOT NULL DEFAULT 'CAMERA',
    tag_status VARCHAR(30) NOT NULL DEFAULT 'ANALYZING',
    publication_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    review_required BOOLEAN NOT NULL DEFAULT FALSE,
    review_deadline_at TIMESTAMP(6),
    archived_at TIMESTAMP(6),
    tag_confirmed_at TIMESTAMP(6),
    heart_count INTEGER NOT NULL DEFAULT 0,
    save_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_ootds_owner FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT ck_ootds_source CHECK (source IN ('CAMERA')),
    CONSTRAINT ck_ootds_tag_status CHECK (
        tag_status IN ('ANALYZING', 'AUTO_UNCONFIRMED', 'CONFIRMED')
    ),
    CONSTRAINT ck_ootds_publication_status CHECK (publication_status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    seller_user_id BIGINT NOT NULL,
    price INTEGER NOT NULL,
    shipping_fee INTEGER NOT NULL DEFAULT 0,
    fee_policy VARCHAR(30) NOT NULL DEFAULT 'SELLER_PAYS',
    main_image_url VARCHAR(500),
    measurements JSONB,
    condition_flags JSONB,
    seller_description TEXT,
    product_status VARCHAR(20) NOT NULL DEFAULT 'ON_SALE',
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_products_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_products_seller FOREIGN KEY (seller_user_id) REFERENCES users (id),
    CONSTRAINT ck_products_fee_policy CHECK (fee_policy IN ('SELLER_PAYS', 'BUYER_PAYS', 'SPLIT')),
    CONSTRAINT ck_products_product_status CHECK (product_status IN ('ON_SALE', 'SOLD', 'HIDDEN'))
);

CREATE TABLE follow_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_user_id BIGINT NOT NULL,
    following_user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    responded_at TIMESTAMP(6),
    CONSTRAINT fk_follow_relationships_follower FOREIGN KEY (follower_user_id) REFERENCES users (id),
    CONSTRAINT fk_follow_relationships_following FOREIGN KEY (following_user_id) REFERENCES users (id),
    CONSTRAINT uk_follow_relationships_follower_following UNIQUE (follower_user_id, following_user_id),
    CONSTRAINT ck_follow_relationships_status CHECK (
        status IN ('REQUESTED', 'ACCEPTED', 'REJECTED', 'CANCELED')
    )
);

CREATE TABLE ootd_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    ootd_id BIGINT NOT NULL,
    reaction_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_ootd_reactions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_ootd_reactions_ootd FOREIGN KEY (ootd_id) REFERENCES ootds (id),
    CONSTRAINT uk_ootd_reactions_user_ootd_type UNIQUE (user_id, ootd_id, reaction_type),
    CONSTRAINT ck_ootd_reactions_type CHECK (reaction_type IN ('HEART', 'SAVE'))
);

CREATE TABLE wishes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    notification_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_wishes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_wishes_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT uk_wishes_user_item UNIQUE (user_id, item_id)
);

CREATE TABLE ootd_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ootd_id BIGINT NOT NULL,
    item_id BIGINT,
    bbox_x NUMERIC(6, 5) NOT NULL,
    bbox_y NUMERIC(6, 5) NOT NULL,
    bbox_width NUMERIC(6, 5) NOT NULL,
    bbox_height NUMERIC(6, 5) NOT NULL,
    label_text VARCHAR(100) NOT NULL,
    source VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    confidence NUMERIC(5, 4),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_ootd_tags_ootd FOREIGN KEY (ootd_id) REFERENCES ootds (id),
    CONSTRAINT fk_ootd_tags_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT ck_ootd_tags_source CHECK (source IN ('MANUAL', 'AI')),
    CONSTRAINT ck_ootd_tags_status CHECK (status IN ('CONFIRMED', 'AUTO_UNCONFIRMED'))
);

CREATE TABLE purchase_intents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    buyer_user_id BIGINT NOT NULL,
    seller_user_id BIGINT NOT NULL,
    delivery_address_id BIGINT NOT NULL,
    product_price INTEGER NOT NULL,
    fee_policy_snapshot VARCHAR(30) NOT NULL,
    buyer_shipping_fee INTEGER NOT NULL DEFAULT 0,
    buyer_service_fee INTEGER NOT NULL DEFAULT 0,
    seller_service_fee INTEGER NOT NULL DEFAULT 0,
    total_payment_amount INTEGER NOT NULL,
    seller_settlement_amount INTEGER NOT NULL,
    payment_authorization_status VARCHAR(30) NOT NULL DEFAULT 'AUTHORIZED',
    payment_authorization_id VARCHAR(100) NOT NULL,
    payment_method_id VARCHAR(100) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SENT',
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_purchase_intents_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_purchase_intents_buyer FOREIGN KEY (buyer_user_id) REFERENCES users (id),
    CONSTRAINT fk_purchase_intents_seller FOREIGN KEY (seller_user_id) REFERENCES users (id),
    CONSTRAINT fk_purchase_intents_delivery_address FOREIGN KEY (delivery_address_id) REFERENCES delivery_addresses (id),
    CONSTRAINT ck_purchase_intents_fee_policy CHECK (
        fee_policy_snapshot IN ('SELLER_PAYS', 'BUYER_PAYS', 'SPLIT')
    ),
    CONSTRAINT ck_purchase_intents_payment_authorization_status CHECK (
        payment_authorization_status IN ('AUTHORIZED', 'CAPTURED', 'RELEASED')
    ),
    CONSTRAINT ck_purchase_intents_status CHECK (
        status IN ('SENT', 'ACCEPTED', 'REJECTED', 'CANCELED', 'EXPIRED')
    )
);

CREATE TABLE purchase_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    proposer_user_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    delivery_address_id BIGINT NOT NULL,
    offer_price INTEGER NOT NULL,
    proposer_shipping_fee INTEGER NOT NULL DEFAULT 0,
    proposer_service_fee INTEGER NOT NULL DEFAULT 0,
    total_payment_amount INTEGER NOT NULL,
    owner_settlement_amount INTEGER NOT NULL,
    payment_authorization_id VARCHAR(100) NOT NULL,
    payment_authorization_status VARCHAR(30) NOT NULL DEFAULT 'AUTHORIZED',
    payment_method_id VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SENT',
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_purchase_offers_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_purchase_offers_proposer FOREIGN KEY (proposer_user_id) REFERENCES users (id),
    CONSTRAINT fk_purchase_offers_owner FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT fk_purchase_offers_delivery_address FOREIGN KEY (delivery_address_id) REFERENCES delivery_addresses (id),
    CONSTRAINT uk_purchase_offers_proposer_item UNIQUE (proposer_user_id, item_id),
    CONSTRAINT ck_purchase_offers_payment_authorization_status CHECK (
        payment_authorization_status IN ('AUTHORIZED', 'CAPTURED', 'RELEASED')
    ),
    CONSTRAINT ck_purchase_offers_status CHECK (
        status IN ('SENT', 'ACCEPTED', 'REJECTED', 'CANCELED', 'EXPIRED')
    )
);

CREATE TABLE trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR(30) NOT NULL,
    source_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    product_id BIGINT,
    buyer_user_id BIGINT NOT NULL,
    seller_user_id BIGINT NOT NULL,
    payment_amount INTEGER NOT NULL,
    buyer_shipping_fee INTEGER NOT NULL DEFAULT 0,
    buyer_service_fee INTEGER NOT NULL DEFAULT 0,
    seller_service_fee INTEGER NOT NULL DEFAULT 0,
    settlement_amount INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PAID',
    delivery_carrier VARCHAR(30),
    custom_delivery_carrier_name VARCHAR(50),
    tracking_number VARCHAR(100),
    payment_method_id VARCHAR(100) NOT NULL,
    payment_authorization_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_trades_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_trades_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_trades_buyer FOREIGN KEY (buyer_user_id) REFERENCES users (id),
    CONSTRAINT fk_trades_seller FOREIGN KEY (seller_user_id) REFERENCES users (id),
    CONSTRAINT ck_trades_source_type CHECK (source_type IN ('PURCHASE_INTENT', 'PURCHASE_OFFER')),
    CONSTRAINT ck_trades_status CHECK (
        status IN ('PAID', 'SHIPPED', 'DELIVERED', 'COMPLETED', 'SETTLED', 'TRANSFERRED')
    ),
    CONSTRAINT ck_trades_delivery_carrier CHECK (
        delivery_carrier IS NULL
        OR delivery_carrier IN ('CJ_LOGISTICS', 'KOREA_POST', 'GS_POSTBOX', 'CU_POST', 'OTHER')
    )
);

CREATE TABLE item_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    previous_owner_user_id BIGINT,
    current_owner_user_id BIGINT NOT NULL,
    trade_id BIGINT,
    ootd_id BIGINT,
    history_type VARCHAR(30) NOT NULL,
    history_description VARCHAR(300),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_item_histories_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_item_histories_previous_owner FOREIGN KEY (previous_owner_user_id) REFERENCES users (id),
    CONSTRAINT fk_item_histories_current_owner FOREIGN KEY (current_owner_user_id) REFERENCES users (id),
    CONSTRAINT fk_item_histories_trade FOREIGN KEY (trade_id) REFERENCES trades (id),
    CONSTRAINT fk_item_histories_ootd FOREIGN KEY (ootd_id) REFERENCES ootds (id)
);

CREATE TABLE product_attached_ootds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    ootd_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_product_attached_ootds_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_product_attached_ootds_ootd FOREIGN KEY (ootd_id) REFERENCES ootds (id),
    CONSTRAINT uk_product_attached_ootds_product_ootd UNIQUE (product_id, ootd_id)
);

CREATE TABLE product_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL,
    seller_user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    reason_type VARCHAR(50) NOT NULL,
    reason_detail VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    created_at TIMESTAMP(6) NOT NULL,
    resolved_at TIMESTAMP(6),
    CONSTRAINT fk_product_reports_reporter FOREIGN KEY (reporter_user_id) REFERENCES users (id),
    CONSTRAINT fk_product_reports_seller FOREIGN KEY (seller_user_id) REFERENCES users (id),
    CONSTRAINT fk_product_reports_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_product_reports_reason_type CHECK (
        reason_type IN (
            'FAKE_PRODUCT',
            'INAPPROPRIATE_PRICE',
            'MISLEADING_DESCRIPTION',
            'PROHIBITED_ITEM',
            'INAPPROPRIATE_IMAGE',
            'OTHER'
        )
    ),
    CONSTRAINT ck_product_reports_status CHECK (status IN ('RECEIVED', 'REVIEWED', 'CLOSED'))
);

CREATE TABLE chat_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    buyer_user_id BIGINT NOT NULL,
    seller_user_id BIGINT NOT NULL,
    last_message VARCHAR(500),
    last_message_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_chat_rooms_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_chat_rooms_buyer FOREIGN KEY (buyer_user_id) REFERENCES users (id),
    CONSTRAINT fk_chat_rooms_seller FOREIGN KEY (seller_user_id) REFERENCES users (id),
    CONSTRAINT uk_chat_rooms_item_buyer_seller UNIQUE (item_id, buyer_user_id, seller_user_id)
);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT NOT NULL,
    sender_user_id BIGINT NOT NULL,
    message_type VARCHAR(20) NOT NULL,
    content TEXT,
    image_url VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_chat_messages_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms (id),
    CONSTRAINT fk_chat_messages_sender FOREIGN KEY (sender_user_id) REFERENCES users (id),
    CONSTRAINT ck_chat_messages_message_type CHECK (message_type IN ('TEXT', 'IMAGE'))
);

CREATE TABLE chat_room_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    last_read_message_id BIGINT,
    unread_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_chat_room_members_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms (id),
    CONSTRAINT fk_chat_room_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_chat_room_members_last_read_message FOREIGN KEY (last_read_message_id) REFERENCES chat_messages (id)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_user_id BIGINT NOT NULL,
    category VARCHAR(30) NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(100) NOT NULL,
    body VARCHAR(500) NOT NULL,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    read_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_notifications_receiver FOREIGN KEY (receiver_user_id) REFERENCES users (id),
    CONSTRAINT ck_notifications_category CHECK (category IN ('NEEDS_ACTION', 'ITEM_NEWS', 'TRADE_STATUS')),
    CONSTRAINT ck_notifications_type CHECK (
        type IN (
            'PRICE_CHANGED',
            'SALE_STARTED',
            'PURCHASE_INTENT_RECEIVED',
            'PURCHASE_OFFER_RECEIVED',
            'PURCHASE_INTENT_ACCEPTED',
            'PURCHASE_OFFER_ACCEPTED',
            'PURCHASE_INTENT_REJECTED',
            'PURCHASE_OFFER_REJECTED',
            'PURCHASE_REQUEST_EXPIRED',
            'PURCHASE_REQUEST_SUPERSEDED',
            'ITEM_SOLD',
            'SHIPPING_STARTED',
            'TRADE_STATUS_CHANGED',
            'FOLLOW_REQUEST_RECEIVED',
            'FOLLOW_REQUEST_ACCEPTED',
            'TAG_REVIEW_REQUIRED'
        )
    ),
    CONSTRAINT ck_notifications_target_type CHECK (
        target_type IN (
            'USER',
            'FOLLOW',
            'OOTD',
            'ITEM',
            'PRODUCT',
            'PURCHASE_INTENT',
            'PURCHASE_OFFER',
            'TRADE',
            'CHAT'
        )
    )
);

CREATE TABLE recent_search_keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    keyword VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_recent_search_keywords_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE recent_viewed_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viewer_user_id BIGINT NOT NULL,
    viewed_user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_recent_viewed_users_viewer FOREIGN KEY (viewer_user_id) REFERENCES users (id),
    CONSTRAINT fk_recent_viewed_users_viewed FOREIGN KEY (viewed_user_id) REFERENCES users (id),
    CONSTRAINT uk_recent_viewed_users_viewer_viewed UNIQUE (viewer_user_id, viewed_user_id)
);

CREATE TABLE user_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_user_id BIGINT NOT NULL,
    blocked_user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_blocks_blocker FOREIGN KEY (blocker_user_id) REFERENCES users (id),
    CONSTRAINT fk_user_blocks_blocked FOREIGN KEY (blocked_user_id) REFERENCES users (id),
    CONSTRAINT uk_user_blocks_blocker_blocked UNIQUE (blocker_user_id, blocked_user_id)
);

CREATE TABLE user_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT,
    reporter_user_id BIGINT NOT NULL,
    reported_user_id BIGINT NOT NULL,
    reason_type VARCHAR(50) NOT NULL,
    reason_detail VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    created_at TIMESTAMP(6) NOT NULL,
    resolved_at TIMESTAMP(6),
    CONSTRAINT fk_user_reports_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms (id),
    CONSTRAINT fk_user_reports_reporter FOREIGN KEY (reporter_user_id) REFERENCES users (id),
    CONSTRAINT fk_user_reports_reported FOREIGN KEY (reported_user_id) REFERENCES users (id),
    CONSTRAINT ck_user_reports_reason_type CHECK (
        reason_type IN ('ABUSIVE_LANGUAGE', 'FRAUD', 'INAPPROPRIATE_CONTENT', 'SPAM', 'OTHER')
    ),
    CONSTRAINT ck_user_reports_status CHECK (status IN ('RECEIVED', 'REVIEWED', 'CLOSED'))
);

CREATE INDEX idx_items_owner_user_id ON items (owner_user_id);
CREATE INDEX idx_ootds_owner_user_id ON ootds (owner_user_id);
CREATE INDEX idx_products_item_id ON products (item_id);
CREATE INDEX idx_products_seller_user_id ON products (seller_user_id);
CREATE INDEX idx_purchase_intents_buyer_user_id ON purchase_intents (buyer_user_id);
CREATE INDEX idx_purchase_intents_seller_user_id ON purchase_intents (seller_user_id);
CREATE INDEX idx_purchase_offers_proposer_user_id ON purchase_offers (proposer_user_id);
CREATE INDEX idx_purchase_offers_owner_user_id ON purchase_offers (owner_user_id);
CREATE INDEX idx_trades_buyer_user_id ON trades (buyer_user_id);
CREATE INDEX idx_trades_seller_user_id ON trades (seller_user_id);
CREATE INDEX idx_notifications_receiver_user_id ON notifications (receiver_user_id);
CREATE INDEX idx_chat_messages_chat_room_id ON chat_messages (chat_room_id);
CREATE INDEX idx_recent_viewed_users_viewer_user_id ON recent_viewed_users (viewer_user_id);
